// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

// 账户
type Account struct {
	// 主键
	ID int64 `json:"id"`
	// 账户所有者
	Owner string `json:"owner"`
	// 账户余额
	Balance int64 `json:"balance"`
	// 货币类型，比如：人民币
	Currency string `json:"currency"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

// 记录所有余额变化
type Entry struct {
	// 主键
	ID int64 `json:"id"`
	// 账户id，关联account的id
	AccountID int64 `json:"account_id"`
	// 变化金额，可正可负
	Amount int64 `json:"amount"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}

// 转账交易记录
type Transfer struct {
	// 主键
	ID int64 `json:"id"`
	// 转账id
	FromAccountID int64 `json:"from_account_id"`
	// 被转账id
	ToAccountID int64 `json:"to_account_id"`
	// 必须为正
	Amount int64 `json:"amount"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
}
